server:
  port: 8080



spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/HRT?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  ##Thymeleaf配置
  #关闭thymeleaf缓存 开发时使用 否则没有实时画面
  thymeleaf:
    cache: false
    #检查模板是否存在，然后再呈现
    check-template-location: true
    #Content-Type值
    servlet.content-type: text/html
    #启用MVC Thymeleaf视图分辨率
    enabled: true
    #应该从解决方案中排除的视图名称的逗号分隔列表
    #    excluded-view-names:
    #模板编码
    mode: HTML
    #在构建URL时预先查看名称的前缀
    prefix: classpath:/templates/
    #查看后缀
    suffix: .html

logging:
  level:
    root: info
  pattern:
    console: "%d - %msg%n"
  config: src/main/resources/logback-spring.xml
  file:
    path: ./logs

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    use-generated-keys: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql