package com.sheng.hrt.dao;

import com.sheng.hrt.po.ChannelLog;
@org.apache.ibatis.annotations.Mapper
public interface ChannelLogMapper extends Mapper<ChannelLog,Long>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_log
     *
     * @mbggenerated
     */
    int insert(ChannelLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_log
     *
     * @mbggenerated
     */
    int insertSelective(ChannelLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_log
     *
     * @mbggenerated
     */
    ChannelLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChannelLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChannelLog record);
}