package com.sheng.hrt.dao;

import com.sheng.hrt.po.DailyStatistic;
@org.apache.ibatis.annotations.Mapper
public interface DailyStatisticMapper extends Mapper<DailyStatistic,Long>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_statistic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_statistic
     *
     * @mbggenerated
     */
    int insert(DailyStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_statistic
     *
     * @mbggenerated
     */
    int insertSelective(DailyStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_statistic
     *
     * @mbggenerated
     */
    DailyStatistic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_statistic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DailyStatistic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_statistic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DailyStatistic record);
}