package com.sheng.hrt.dao;

import com.github.pagehelper.Page;
import com.sheng.hrt.po.DailyStatistic;
import com.sheng.hrt.po.Menu;

import java.util.List;
import java.util.Map;

@org.apache.ibatis.annotations.Mapper
public interface MenuMapper extends Mapper<Menu,Integer>{
//    @Override
//    List<Menu> queryPageList(Map<String, Object> params);
//
//    @Override
//    List<Menu> selectALL();
//
//    @Override
//    List<Map<String, Object>> queryList(Map<String, Object> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated
     */
    Menu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Menu record);

}