package com.sheng.hrt.dao;

import com.sheng.hrt.po.TestConfig;
@org.apache.ibatis.annotations.Mapper
public interface TestConfigMapper extends Mapper<TestConfig,Long>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testConfig
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long testId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testConfig
     *
     * @mbggenerated
     */
    int insert(TestConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testConfig
     *
     * @mbggenerated
     */
    int insertSelective(TestConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testConfig
     *
     * @mbggenerated
     */
    TestConfig selectByPrimaryKey(Long testId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testConfig
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TestConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testConfig
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestConfig record);
}