package com.sheng.hrt.dao;

import com.sheng.hrt.po.TestPlan;
@org.apache.ibatis.annotations.Mapper
public interface TestPlanMapper extends Mapper<TestPlan,Long>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testPlan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testPlan
     *
     * @mbggenerated
     */
    int insert(TestPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testPlan
     *
     * @mbggenerated
     */
    int insertSelective(TestPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testPlan
     *
     * @mbggenerated
     */
    TestPlan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testPlan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TestPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testPlan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestPlan record);
}