package com.sheng.hrt.dao;

import com.sheng.hrt.po.ThirdChannelLog;
@org.apache.ibatis.annotations.Mapper
public interface ThirdChannelLogMapper extends Mapper<ThirdChannelLog,Long>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_channel_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_channel_log
     *
     * @mbggenerated
     */
    int insert(ThirdChannelLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_channel_log
     *
     * @mbggenerated
     */
    int insertSelective(ThirdChannelLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_channel_log
     *
     * @mbggenerated
     */
    ThirdChannelLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_channel_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ThirdChannelLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_channel_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ThirdChannelLog record);
}