package com.sheng.hrt.po;

public class Application {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_id
     *
     * @mbggenerated
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_code
     *
     * @mbggenerated
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_subtitle
     *
     * @mbggenerated
     */
    private String appSubtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_img
     *
     * @mbggenerated
     */
    private String appImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_url
     *
     * @mbggenerated
     */
    private String appUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_status
     *
     * @mbggenerated
     */
    private Boolean appStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.last_operator_id
     *
     * @mbggenerated
     */
    private Long lastOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.test_name
     *
     * @mbggenerated
     */
    private String testName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_id
     *
     * @return the value of application.app_id
     *
     * @mbggenerated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_id
     *
     * @param appId the value for application.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_name
     *
     * @return the value of application.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_name
     *
     * @param appName the value for application.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_code
     *
     * @return the value of application.app_code
     *
     * @mbggenerated
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_code
     *
     * @param appCode the value for application.app_code
     *
     * @mbggenerated
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_subtitle
     *
     * @return the value of application.app_subtitle
     *
     * @mbggenerated
     */
    public String getAppSubtitle() {
        return appSubtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_subtitle
     *
     * @param appSubtitle the value for application.app_subtitle
     *
     * @mbggenerated
     */
    public void setAppSubtitle(String appSubtitle) {
        this.appSubtitle = appSubtitle == null ? null : appSubtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_img
     *
     * @return the value of application.app_img
     *
     * @mbggenerated
     */
    public String getAppImg() {
        return appImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_img
     *
     * @param appImg the value for application.app_img
     *
     * @mbggenerated
     */
    public void setAppImg(String appImg) {
        this.appImg = appImg == null ? null : appImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_url
     *
     * @return the value of application.app_url
     *
     * @mbggenerated
     */
    public String getAppUrl() {
        return appUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_url
     *
     * @param appUrl the value for application.app_url
     *
     * @mbggenerated
     */
    public void setAppUrl(String appUrl) {
        this.appUrl = appUrl == null ? null : appUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.sort
     *
     * @return the value of application.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.sort
     *
     * @param sort the value for application.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_status
     *
     * @return the value of application.app_status
     *
     * @mbggenerated
     */
    public Boolean getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_status
     *
     * @param appStatus the value for application.app_status
     *
     * @mbggenerated
     */
    public void setAppStatus(Boolean appStatus) {
        this.appStatus = appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.last_operator_id
     *
     * @return the value of application.last_operator_id
     *
     * @mbggenerated
     */
    public Long getLastOperatorId() {
        return lastOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.last_operator_id
     *
     * @param lastOperatorId the value for application.last_operator_id
     *
     * @mbggenerated
     */
    public void setLastOperatorId(Long lastOperatorId) {
        this.lastOperatorId = lastOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.test_name
     *
     * @return the value of application.test_name
     *
     * @mbggenerated
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.test_name
     *
     * @param testName the value for application.test_name
     *
     * @mbggenerated
     */
    public void setTestName(String testName) {
        this.testName = testName == null ? null : testName.trim();
    }
}