package com.sheng.hrt.po;

public class Channel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channel_id
     *
     * @mbggenerated
     */
    private Long channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channel_name
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channel_daily_threshold
     *
     * @mbggenerated
     */
    private Long channelDailyThreshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channel_daily_user_threshold
     *
     * @mbggenerated
     */
    private Long channelDailyUserThreshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channel_start_time
     *
     * @mbggenerated
     */
    private Long channelStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channel_end_time
     *
     * @mbggenerated
     */
    private Long channelEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.point_id
     *
     * @mbggenerated
     */
    private Long pointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.channel_status
     *
     * @mbggenerated
     */
    private Boolean channelStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.test_name
     *
     * @mbggenerated
     */
    private Integer testName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channel_id
     *
     * @return the value of channel.channel_id
     *
     * @mbggenerated
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channel_id
     *
     * @param channelId the value for channel.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channel_name
     *
     * @return the value of channel.channel_name
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channel_name
     *
     * @param channelName the value for channel.channel_name
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channel_daily_threshold
     *
     * @return the value of channel.channel_daily_threshold
     *
     * @mbggenerated
     */
    public Long getChannelDailyThreshold() {
        return channelDailyThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channel_daily_threshold
     *
     * @param channelDailyThreshold the value for channel.channel_daily_threshold
     *
     * @mbggenerated
     */
    public void setChannelDailyThreshold(Long channelDailyThreshold) {
        this.channelDailyThreshold = channelDailyThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channel_daily_user_threshold
     *
     * @return the value of channel.channel_daily_user_threshold
     *
     * @mbggenerated
     */
    public Long getChannelDailyUserThreshold() {
        return channelDailyUserThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channel_daily_user_threshold
     *
     * @param channelDailyUserThreshold the value for channel.channel_daily_user_threshold
     *
     * @mbggenerated
     */
    public void setChannelDailyUserThreshold(Long channelDailyUserThreshold) {
        this.channelDailyUserThreshold = channelDailyUserThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channel_start_time
     *
     * @return the value of channel.channel_start_time
     *
     * @mbggenerated
     */
    public Long getChannelStartTime() {
        return channelStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channel_start_time
     *
     * @param channelStartTime the value for channel.channel_start_time
     *
     * @mbggenerated
     */
    public void setChannelStartTime(Long channelStartTime) {
        this.channelStartTime = channelStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channel_end_time
     *
     * @return the value of channel.channel_end_time
     *
     * @mbggenerated
     */
    public Long getChannelEndTime() {
        return channelEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channel_end_time
     *
     * @param channelEndTime the value for channel.channel_end_time
     *
     * @mbggenerated
     */
    public void setChannelEndTime(Long channelEndTime) {
        this.channelEndTime = channelEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.point_id
     *
     * @return the value of channel.point_id
     *
     * @mbggenerated
     */
    public Long getPointId() {
        return pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.point_id
     *
     * @param pointId the value for channel.point_id
     *
     * @mbggenerated
     */
    public void setPointId(Long pointId) {
        this.pointId = pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.channel_status
     *
     * @return the value of channel.channel_status
     *
     * @mbggenerated
     */
    public Boolean getChannelStatus() {
        return channelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.channel_status
     *
     * @param channelStatus the value for channel.channel_status
     *
     * @mbggenerated
     */
    public void setChannelStatus(Boolean channelStatus) {
        this.channelStatus = channelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.test_name
     *
     * @return the value of channel.test_name
     *
     * @mbggenerated
     */
    public Integer getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.test_name
     *
     * @param testName the value for channel.test_name
     *
     * @mbggenerated
     */
    public void setTestName(Integer testName) {
        this.testName = testName;
    }
}