package com.sheng.hrt.po;

import java.util.Date;

public class DailyStatistic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_statistic.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_statistic.point_id
     *
     * @mbggenerated
     */
    private Long pointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_statistic.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_statistic.issue_amount
     *
     * @mbggenerated
     */
    private Long issueAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_statistic.consume_amount
     *
     * @mbggenerated
     */
    private Long consumeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_statistic.commision_amount
     *
     * @mbggenerated
     */
    private Long commisionAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_statistic.register_num
     *
     * @mbggenerated
     */
    private Integer registerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_statistic.issue_count
     *
     * @mbggenerated
     */
    private Integer issueCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_statistic.issue_people_num
     *
     * @mbggenerated
     */
    private Integer issuePeopleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_statistic.test_name
     *
     * @mbggenerated
     */
    private Integer testName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_statistic.id
     *
     * @return the value of daily_statistic.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_statistic.id
     *
     * @param id the value for daily_statistic.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_statistic.point_id
     *
     * @return the value of daily_statistic.point_id
     *
     * @mbggenerated
     */
    public Long getPointId() {
        return pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_statistic.point_id
     *
     * @param pointId the value for daily_statistic.point_id
     *
     * @mbggenerated
     */
    public void setPointId(Long pointId) {
        this.pointId = pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_statistic.create_time
     *
     * @return the value of daily_statistic.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_statistic.create_time
     *
     * @param createTime the value for daily_statistic.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_statistic.issue_amount
     *
     * @return the value of daily_statistic.issue_amount
     *
     * @mbggenerated
     */
    public Long getIssueAmount() {
        return issueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_statistic.issue_amount
     *
     * @param issueAmount the value for daily_statistic.issue_amount
     *
     * @mbggenerated
     */
    public void setIssueAmount(Long issueAmount) {
        this.issueAmount = issueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_statistic.consume_amount
     *
     * @return the value of daily_statistic.consume_amount
     *
     * @mbggenerated
     */
    public Long getConsumeAmount() {
        return consumeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_statistic.consume_amount
     *
     * @param consumeAmount the value for daily_statistic.consume_amount
     *
     * @mbggenerated
     */
    public void setConsumeAmount(Long consumeAmount) {
        this.consumeAmount = consumeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_statistic.commision_amount
     *
     * @return the value of daily_statistic.commision_amount
     *
     * @mbggenerated
     */
    public Long getCommisionAmount() {
        return commisionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_statistic.commision_amount
     *
     * @param commisionAmount the value for daily_statistic.commision_amount
     *
     * @mbggenerated
     */
    public void setCommisionAmount(Long commisionAmount) {
        this.commisionAmount = commisionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_statistic.register_num
     *
     * @return the value of daily_statistic.register_num
     *
     * @mbggenerated
     */
    public Integer getRegisterNum() {
        return registerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_statistic.register_num
     *
     * @param registerNum the value for daily_statistic.register_num
     *
     * @mbggenerated
     */
    public void setRegisterNum(Integer registerNum) {
        this.registerNum = registerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_statistic.issue_count
     *
     * @return the value of daily_statistic.issue_count
     *
     * @mbggenerated
     */
    public Integer getIssueCount() {
        return issueCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_statistic.issue_count
     *
     * @param issueCount the value for daily_statistic.issue_count
     *
     * @mbggenerated
     */
    public void setIssueCount(Integer issueCount) {
        this.issueCount = issueCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_statistic.issue_people_num
     *
     * @return the value of daily_statistic.issue_people_num
     *
     * @mbggenerated
     */
    public Integer getIssuePeopleNum() {
        return issuePeopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_statistic.issue_people_num
     *
     * @param issuePeopleNum the value for daily_statistic.issue_people_num
     *
     * @mbggenerated
     */
    public void setIssuePeopleNum(Integer issuePeopleNum) {
        this.issuePeopleNum = issuePeopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_statistic.test_name
     *
     * @return the value of daily_statistic.test_name
     *
     * @mbggenerated
     */
    public Integer getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_statistic.test_name
     *
     * @param testName the value for daily_statistic.test_name
     *
     * @mbggenerated
     */
    public void setTestName(Integer testName) {
        this.testName = testName;
    }
}