package com.sheng.hrt.po;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.navName
     *
     * @mbggenerated
     */
    private String navname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.navName
     *
     * @return the value of menu.navName
     *
     * @mbggenerated
     */
    public String getNavname() {
        return navname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.navName
     *
     * @param navname the value for menu.navName
     *
     * @mbggenerated
     */
    public void setNavname(String navname) {
        this.navname = navname == null ? null : navname.trim();
    }
}