package com.sheng.hrt.po;

public class Point {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.point_id
     *
     * @mbggenerated
     */
    private Long pointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.point_name
     *
     * @mbggenerated
     */
    private String pointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.point_exchange_rate
     *
     * @mbggenerated
     */
    private Integer pointExchangeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.point_code
     *
     * @mbggenerated
     */
    private String pointCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.test_name
     *
     * @mbggenerated
     */
    private Integer testName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.point_id
     *
     * @return the value of point.point_id
     *
     * @mbggenerated
     */
    public Long getPointId() {
        return pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.point_id
     *
     * @param pointId the value for point.point_id
     *
     * @mbggenerated
     */
    public void setPointId(Long pointId) {
        this.pointId = pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.point_name
     *
     * @return the value of point.point_name
     *
     * @mbggenerated
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.point_name
     *
     * @param pointName the value for point.point_name
     *
     * @mbggenerated
     */
    public void setPointName(String pointName) {
        this.pointName = pointName == null ? null : pointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.point_exchange_rate
     *
     * @return the value of point.point_exchange_rate
     *
     * @mbggenerated
     */
    public Integer getPointExchangeRate() {
        return pointExchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.point_exchange_rate
     *
     * @param pointExchangeRate the value for point.point_exchange_rate
     *
     * @mbggenerated
     */
    public void setPointExchangeRate(Integer pointExchangeRate) {
        this.pointExchangeRate = pointExchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.create_time
     *
     * @return the value of point.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.create_time
     *
     * @param createTime the value for point.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.point_code
     *
     * @return the value of point.point_code
     *
     * @mbggenerated
     */
    public String getPointCode() {
        return pointCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.point_code
     *
     * @param pointCode the value for point.point_code
     *
     * @mbggenerated
     */
    public void setPointCode(String pointCode) {
        this.pointCode = pointCode == null ? null : pointCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.test_name
     *
     * @return the value of point.test_name
     *
     * @mbggenerated
     */
    public Integer getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.test_name
     *
     * @param testName the value for point.test_name
     *
     * @mbggenerated
     */
    public void setTestName(Integer testName) {
        this.testName = testName;
    }
}