package com.sheng.hrt.po;

public class TestPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testPlan.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testPlan.application_id
     *
     * @mbggenerated
     */
    private Long applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testPlan.channel_id
     *
     * @mbggenerated
     */
    private Long channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testPlan.third_channel_id
     *
     * @mbggenerated
     */
    private Long thirdChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testPlan.point_id
     *
     * @mbggenerated
     */
    private Long pointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testPlan.test_id
     *
     * @mbggenerated
     */
    private Long testId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testPlan.id
     *
     * @return the value of testPlan.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testPlan.id
     *
     * @param id the value for testPlan.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testPlan.application_id
     *
     * @return the value of testPlan.application_id
     *
     * @mbggenerated
     */
    public Long getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testPlan.application_id
     *
     * @param applicationId the value for testPlan.application_id
     *
     * @mbggenerated
     */
    public void setApplicationId(Long applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testPlan.channel_id
     *
     * @return the value of testPlan.channel_id
     *
     * @mbggenerated
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testPlan.channel_id
     *
     * @param channelId the value for testPlan.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testPlan.third_channel_id
     *
     * @return the value of testPlan.third_channel_id
     *
     * @mbggenerated
     */
    public Long getThirdChannelId() {
        return thirdChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testPlan.third_channel_id
     *
     * @param thirdChannelId the value for testPlan.third_channel_id
     *
     * @mbggenerated
     */
    public void setThirdChannelId(Long thirdChannelId) {
        this.thirdChannelId = thirdChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testPlan.point_id
     *
     * @return the value of testPlan.point_id
     *
     * @mbggenerated
     */
    public Long getPointId() {
        return pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testPlan.point_id
     *
     * @param pointId the value for testPlan.point_id
     *
     * @mbggenerated
     */
    public void setPointId(Long pointId) {
        this.pointId = pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testPlan.test_id
     *
     * @return the value of testPlan.test_id
     *
     * @mbggenerated
     */
    public Long getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testPlan.test_id
     *
     * @param testId the value for testPlan.test_id
     *
     * @mbggenerated
     */
    public void setTestId(Long testId) {
        this.testId = testId;
    }
}