package com.sheng.hrt.po;

public class TestConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testConfig.test_id
     *
     * @mbggenerated
     */
    private Long testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testConfig.test_name
     *
     * @mbggenerated
     */
    private String testName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testConfig.test_time
     *
     * @mbggenerated
     */
    private String testTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testConfig.test_id
     *
     * @return the value of testConfig.test_id
     *
     * @mbggenerated
     */
    public Long getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testConfig.test_id
     *
     * @param testId the value for testConfig.test_id
     *
     * @mbggenerated
     */
    public void setTestId(Long testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testConfig.test_name
     *
     * @return the value of testConfig.test_name
     *
     * @mbggenerated
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testConfig.test_name
     *
     * @param testName the value for testConfig.test_name
     *
     * @mbggenerated
     */
    public void setTestName(String testName) {
        this.testName = testName == null ? null : testName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testConfig.test_time
     *
     * @return the value of testConfig.test_time
     *
     * @mbggenerated
     */
    public String getTestTime() {
        return testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testConfig.test_time
     *
     * @param testTime the value for testConfig.test_time
     *
     * @mbggenerated
     */
    public void setTestTime(String testTime) {
        this.testTime = testTime == null ? null : testTime.trim();
    }
}