package com.sheng.hrt.po;

public class ThirdChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel.channel_id
     *
     * @mbggenerated
     */
    private Long channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel.channel_name
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel.channel_daily_threshold
     *
     * @mbggenerated
     */
    private Long channelDailyThreshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel.channel_daily_user_threshold
     *
     * @mbggenerated
     */
    private Long channelDailyUserThreshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel.channel_key
     *
     * @mbggenerated
     */
    private String channelKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel.point_name
     *
     * @mbggenerated
     */
    private String pointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel.point_exchange_rate
     *
     * @mbggenerated
     */
    private Integer pointExchangeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel.charge_ratio
     *
     * @mbggenerated
     */
    private Integer chargeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel.last_operator_id
     *
     * @mbggenerated
     */
    private Long lastOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel.channel_status
     *
     * @mbggenerated
     */
    private Boolean channelStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel.test_name
     *
     * @mbggenerated
     */
    private Integer testName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel.channel_id
     *
     * @return the value of third_channel.channel_id
     *
     * @mbggenerated
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel.channel_id
     *
     * @param channelId the value for third_channel.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel.channel_name
     *
     * @return the value of third_channel.channel_name
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel.channel_name
     *
     * @param channelName the value for third_channel.channel_name
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel.channel_daily_threshold
     *
     * @return the value of third_channel.channel_daily_threshold
     *
     * @mbggenerated
     */
    public Long getChannelDailyThreshold() {
        return channelDailyThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel.channel_daily_threshold
     *
     * @param channelDailyThreshold the value for third_channel.channel_daily_threshold
     *
     * @mbggenerated
     */
    public void setChannelDailyThreshold(Long channelDailyThreshold) {
        this.channelDailyThreshold = channelDailyThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel.channel_daily_user_threshold
     *
     * @return the value of third_channel.channel_daily_user_threshold
     *
     * @mbggenerated
     */
    public Long getChannelDailyUserThreshold() {
        return channelDailyUserThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel.channel_daily_user_threshold
     *
     * @param channelDailyUserThreshold the value for third_channel.channel_daily_user_threshold
     *
     * @mbggenerated
     */
    public void setChannelDailyUserThreshold(Long channelDailyUserThreshold) {
        this.channelDailyUserThreshold = channelDailyUserThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel.channel_key
     *
     * @return the value of third_channel.channel_key
     *
     * @mbggenerated
     */
    public String getChannelKey() {
        return channelKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel.channel_key
     *
     * @param channelKey the value for third_channel.channel_key
     *
     * @mbggenerated
     */
    public void setChannelKey(String channelKey) {
        this.channelKey = channelKey == null ? null : channelKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel.point_name
     *
     * @return the value of third_channel.point_name
     *
     * @mbggenerated
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel.point_name
     *
     * @param pointName the value for third_channel.point_name
     *
     * @mbggenerated
     */
    public void setPointName(String pointName) {
        this.pointName = pointName == null ? null : pointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel.point_exchange_rate
     *
     * @return the value of third_channel.point_exchange_rate
     *
     * @mbggenerated
     */
    public Integer getPointExchangeRate() {
        return pointExchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel.point_exchange_rate
     *
     * @param pointExchangeRate the value for third_channel.point_exchange_rate
     *
     * @mbggenerated
     */
    public void setPointExchangeRate(Integer pointExchangeRate) {
        this.pointExchangeRate = pointExchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel.charge_ratio
     *
     * @return the value of third_channel.charge_ratio
     *
     * @mbggenerated
     */
    public Integer getChargeRatio() {
        return chargeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel.charge_ratio
     *
     * @param chargeRatio the value for third_channel.charge_ratio
     *
     * @mbggenerated
     */
    public void setChargeRatio(Integer chargeRatio) {
        this.chargeRatio = chargeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel.last_operator_id
     *
     * @return the value of third_channel.last_operator_id
     *
     * @mbggenerated
     */
    public Long getLastOperatorId() {
        return lastOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel.last_operator_id
     *
     * @param lastOperatorId the value for third_channel.last_operator_id
     *
     * @mbggenerated
     */
    public void setLastOperatorId(Long lastOperatorId) {
        this.lastOperatorId = lastOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel.channel_status
     *
     * @return the value of third_channel.channel_status
     *
     * @mbggenerated
     */
    public Boolean getChannelStatus() {
        return channelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel.channel_status
     *
     * @param channelStatus the value for third_channel.channel_status
     *
     * @mbggenerated
     */
    public void setChannelStatus(Boolean channelStatus) {
        this.channelStatus = channelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel.create_time
     *
     * @return the value of third_channel.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel.create_time
     *
     * @param createTime the value for third_channel.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel.test_name
     *
     * @return the value of third_channel.test_name
     *
     * @mbggenerated
     */
    public Integer getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel.test_name
     *
     * @param testName the value for third_channel.test_name
     *
     * @mbggenerated
     */
    public void setTestName(Integer testName) {
        this.testName = testName;
    }
}