package com.sheng.hrt.po;

public class ThirdChannelLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel_log.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel_log.state_change
     *
     * @mbggenerated
     */
    private String stateChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel_log.operator_id
     *
     * @mbggenerated
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel_log.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_channel_log.test_name
     *
     * @mbggenerated
     */
    private Integer testName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel_log.id
     *
     * @return the value of third_channel_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel_log.id
     *
     * @param id the value for third_channel_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel_log.create_time
     *
     * @return the value of third_channel_log.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel_log.create_time
     *
     * @param createTime the value for third_channel_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel_log.state_change
     *
     * @return the value of third_channel_log.state_change
     *
     * @mbggenerated
     */
    public String getStateChange() {
        return stateChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel_log.state_change
     *
     * @param stateChange the value for third_channel_log.state_change
     *
     * @mbggenerated
     */
    public void setStateChange(String stateChange) {
        this.stateChange = stateChange == null ? null : stateChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel_log.operator_id
     *
     * @return the value of third_channel_log.operator_id
     *
     * @mbggenerated
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel_log.operator_id
     *
     * @param operatorId the value for third_channel_log.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel_log.remark
     *
     * @return the value of third_channel_log.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel_log.remark
     *
     * @param remark the value for third_channel_log.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_channel_log.test_name
     *
     * @return the value of third_channel_log.test_name
     *
     * @mbggenerated
     */
    public Integer getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_channel_log.test_name
     *
     * @param testName the value for third_channel_log.test_name
     *
     * @mbggenerated
     */
    public void setTestName(Integer testName) {
        this.testName = testName;
    }
}