package com.sheng.hrt.po;

import java.util.Date;

public class UserPointBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.bill_id
     *
     * @mbggenerated
     */
    private Long billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.point_id
     *
     * @mbggenerated
     */
    private Long pointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.channel_begin_points
     *
     * @mbggenerated
     */
    private Long channelBeginPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.channel_changed_points
     *
     * @mbggenerated
     */
    private Long channelChangedPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.channel_end_points
     *
     * @mbggenerated
     */
    private Long channelEndPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.bill_type
     *
     * @mbggenerated
     */
    private Boolean billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.relation_id
     *
     * @mbggenerated
     */
    private Long relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.channel_name
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.change_reason
     *
     * @mbggenerated
     */
    private String changeReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.commission_ratio
     *
     * @mbggenerated
     */
    private Integer commissionRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.fee_ratio
     *
     * @mbggenerated
     */
    private Integer feeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.first_charge_mark
     *
     * @mbggenerated
     */
    private Boolean firstChargeMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.user_begin_points
     *
     * @mbggenerated
     */
    private Long userBeginPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.user_changed_points
     *
     * @mbggenerated
     */
    private Long userChangedPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.user_end_points
     *
     * @mbggenerated
     */
    private Long userEndPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.channel_id
     *
     * @mbggenerated
     */
    private Long channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.target_point_name
     *
     * @mbggenerated
     */
    private String targetPointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point_bill.test_name
     *
     * @mbggenerated
     */
    private Integer testName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.bill_id
     *
     * @return the value of user_point_bill.bill_id
     *
     * @mbggenerated
     */
    public Long getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.bill_id
     *
     * @param billId the value for user_point_bill.bill_id
     *
     * @mbggenerated
     */
    public void setBillId(Long billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.point_id
     *
     * @return the value of user_point_bill.point_id
     *
     * @mbggenerated
     */
    public Long getPointId() {
        return pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.point_id
     *
     * @param pointId the value for user_point_bill.point_id
     *
     * @mbggenerated
     */
    public void setPointId(Long pointId) {
        this.pointId = pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.channel_begin_points
     *
     * @return the value of user_point_bill.channel_begin_points
     *
     * @mbggenerated
     */
    public Long getChannelBeginPoints() {
        return channelBeginPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.channel_begin_points
     *
     * @param channelBeginPoints the value for user_point_bill.channel_begin_points
     *
     * @mbggenerated
     */
    public void setChannelBeginPoints(Long channelBeginPoints) {
        this.channelBeginPoints = channelBeginPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.channel_changed_points
     *
     * @return the value of user_point_bill.channel_changed_points
     *
     * @mbggenerated
     */
    public Long getChannelChangedPoints() {
        return channelChangedPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.channel_changed_points
     *
     * @param channelChangedPoints the value for user_point_bill.channel_changed_points
     *
     * @mbggenerated
     */
    public void setChannelChangedPoints(Long channelChangedPoints) {
        this.channelChangedPoints = channelChangedPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.channel_end_points
     *
     * @return the value of user_point_bill.channel_end_points
     *
     * @mbggenerated
     */
    public Long getChannelEndPoints() {
        return channelEndPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.channel_end_points
     *
     * @param channelEndPoints the value for user_point_bill.channel_end_points
     *
     * @mbggenerated
     */
    public void setChannelEndPoints(Long channelEndPoints) {
        this.channelEndPoints = channelEndPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.bill_type
     *
     * @return the value of user_point_bill.bill_type
     *
     * @mbggenerated
     */
    public Boolean getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.bill_type
     *
     * @param billType the value for user_point_bill.bill_type
     *
     * @mbggenerated
     */
    public void setBillType(Boolean billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.relation_id
     *
     * @return the value of user_point_bill.relation_id
     *
     * @mbggenerated
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.relation_id
     *
     * @param relationId the value for user_point_bill.relation_id
     *
     * @mbggenerated
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.user_id
     *
     * @return the value of user_point_bill.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.user_id
     *
     * @param userId the value for user_point_bill.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.channel_name
     *
     * @return the value of user_point_bill.channel_name
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.channel_name
     *
     * @param channelName the value for user_point_bill.channel_name
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.create_time
     *
     * @return the value of user_point_bill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.create_time
     *
     * @param createTime the value for user_point_bill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.app_name
     *
     * @return the value of user_point_bill.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.app_name
     *
     * @param appName the value for user_point_bill.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.change_reason
     *
     * @return the value of user_point_bill.change_reason
     *
     * @mbggenerated
     */
    public String getChangeReason() {
        return changeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.change_reason
     *
     * @param changeReason the value for user_point_bill.change_reason
     *
     * @mbggenerated
     */
    public void setChangeReason(String changeReason) {
        this.changeReason = changeReason == null ? null : changeReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.commission_ratio
     *
     * @return the value of user_point_bill.commission_ratio
     *
     * @mbggenerated
     */
    public Integer getCommissionRatio() {
        return commissionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.commission_ratio
     *
     * @param commissionRatio the value for user_point_bill.commission_ratio
     *
     * @mbggenerated
     */
    public void setCommissionRatio(Integer commissionRatio) {
        this.commissionRatio = commissionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.fee_ratio
     *
     * @return the value of user_point_bill.fee_ratio
     *
     * @mbggenerated
     */
    public Integer getFeeRatio() {
        return feeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.fee_ratio
     *
     * @param feeRatio the value for user_point_bill.fee_ratio
     *
     * @mbggenerated
     */
    public void setFeeRatio(Integer feeRatio) {
        this.feeRatio = feeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.first_charge_mark
     *
     * @return the value of user_point_bill.first_charge_mark
     *
     * @mbggenerated
     */
    public Boolean getFirstChargeMark() {
        return firstChargeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.first_charge_mark
     *
     * @param firstChargeMark the value for user_point_bill.first_charge_mark
     *
     * @mbggenerated
     */
    public void setFirstChargeMark(Boolean firstChargeMark) {
        this.firstChargeMark = firstChargeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.user_begin_points
     *
     * @return the value of user_point_bill.user_begin_points
     *
     * @mbggenerated
     */
    public Long getUserBeginPoints() {
        return userBeginPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.user_begin_points
     *
     * @param userBeginPoints the value for user_point_bill.user_begin_points
     *
     * @mbggenerated
     */
    public void setUserBeginPoints(Long userBeginPoints) {
        this.userBeginPoints = userBeginPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.user_changed_points
     *
     * @return the value of user_point_bill.user_changed_points
     *
     * @mbggenerated
     */
    public Long getUserChangedPoints() {
        return userChangedPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.user_changed_points
     *
     * @param userChangedPoints the value for user_point_bill.user_changed_points
     *
     * @mbggenerated
     */
    public void setUserChangedPoints(Long userChangedPoints) {
        this.userChangedPoints = userChangedPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.user_end_points
     *
     * @return the value of user_point_bill.user_end_points
     *
     * @mbggenerated
     */
    public Long getUserEndPoints() {
        return userEndPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.user_end_points
     *
     * @param userEndPoints the value for user_point_bill.user_end_points
     *
     * @mbggenerated
     */
    public void setUserEndPoints(Long userEndPoints) {
        this.userEndPoints = userEndPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.channel_id
     *
     * @return the value of user_point_bill.channel_id
     *
     * @mbggenerated
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.channel_id
     *
     * @param channelId the value for user_point_bill.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.target_point_name
     *
     * @return the value of user_point_bill.target_point_name
     *
     * @mbggenerated
     */
    public String getTargetPointName() {
        return targetPointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.target_point_name
     *
     * @param targetPointName the value for user_point_bill.target_point_name
     *
     * @mbggenerated
     */
    public void setTargetPointName(String targetPointName) {
        this.targetPointName = targetPointName == null ? null : targetPointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point_bill.test_name
     *
     * @return the value of user_point_bill.test_name
     *
     * @mbggenerated
     */
    public Integer getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point_bill.test_name
     *
     * @param testName the value for user_point_bill.test_name
     *
     * @mbggenerated
     */
    public void setTestName(Integer testName) {
        this.testName = testName;
    }
}